# .github/workflows/test.yml
name: Probar Mi Acción de Cypress

# Cuándo se ejecutará esta pista de pruebas.
# ¡La indentación es CRUCIAL aquí!
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run My Cypress Action
        # ¡IMPORTANTE! 'uses: ./' le dice a GitHub que use la acción definida en action.yml
        # en la raíz de ESTE repositorio (el repositorio de la acción en sí).
        uses: ./ 
        with:
          # ¡MUY IMPORTANTE! El slack-webhook debe ser un SECRETO.
          # No pegues el valor directo aquí. Lo crearemos en el paso 6.
          slack-webhook: ${{ secrets.TEST_SLACK_WEBHOOK }} 
          # Puedes personalizar otros inputs si quieres probarlos:
          # node-version: '20'
          # cypress-command: 'npx cypress run --browser chrome' 
          # slack-username: 'TestBot'
          # slack-title: 'Resultados de Prueba de la Acción'
          # continue-on-cypress-error: 'false'